### ISSUE TITLE
Server doesn't parse query string

### ISSUE THREAD

**Issue by EffeErre** [Vexu/routez#10]
Hi!

In file routez/http/parser.zig there's this code (line 24):

``` zig
    if (req.path.len > 1) {
        const uri = try Uri.parse(ctx.buf[cur .. ctx.index - 1], true);
        req.path = try Uri.resolvePath(req.headers.list.allocator, uri.path);
        req.query = uri.query;
    } else {
        req.path = try req.headers.list.allocator.dupe(u8, ctx.buf[cur .. ctx.index - 1]);
    }
```

I don't understand why you do this test, as it will always use the else branch (req.path is initialized to "" at this point). Else brach will copy both path and query string in req.path, leaving req.query = "".

I tested removing the if / else and it jost works as expected:

``` zig
    const uri = try Uri.parse(ctx.buf[cur .. ctx.index - 1], true);
    req.path = try Uri.resolvePath(req.headers.list.allocator, uri.path);
    req.query = uri.query;

```

Maybe I'm missing some other aspect?

Thanks!

**Comment by Vexu** [comment]
I have no idea why that condition was there so I just removed it.
