### ISSUE TITLE
Quiting from server has delay

### ISSUE THREAD

**Issue by tonis2** [Vexu/routez#13]
Hi,

When I create a debug server and try to fire some route, for example I run the `basic.zig` from examples and ping `http://localhost:8080/counter`.

Now I want to restart my server, for example I made some changes in the code, 
I close the server with `ctrl+c` and rerun it, then I get error `error: AddressInUse`

The server address becomes available and is released after some minutes of waiting, so how could I close my server immediately ?

My OS is Ubuntu 20.10

**Comment by Vexu** [comment]
This can now be fixed by passing `.reuse_address = true` to `StreamServer.init()` in `server.zig:89`, this option did not yet exist when I built this.

**Comment by tonis2** [comment]
Thanks, this fixed my problem
