### ISSUE TITLE
`zig build basic`  fails with error in build.zig

### ISSUE THREAD

**Issue by samusz** [Vexu/routez#22]
Hi, 
will trying out your code : 
```
zig build basic
./build.zig:17:9: error: no member named 'path' in struct 'std.build.Pkg'
        .path = .{ .path = "src/routez.zig" },
        ^
```
Since I am new to zig, I have no clue to help out debugging, but thought to report it here anyway. 

When looking at this kind of error on other zig projects, it seems this is related to changes in build from 0.9 to zig version 0.10 with I am currently running. 
```
zig version 
0.10.0-dev.3456+40babaa53
```

Best.

**Comment by Vexu** [comment]
The `build.zig` error was an easy rename, the bigger problem was the usage of `anytype` fields which were removed six months ago. 7e8ac33a8147a29dbbe86f58a1bec8000a8a4b42 should now build with latest Zig.
